=== Global19/DtdAnalyzer/test/xml2json/sample3.dtd
<!--    
  This is an example/test DTD for the XML-to-JSON features of the DtdAnalyzer.
  This DTD tests the ability to implement some of the templates in
  an external custom stylesheet.
  
  The elements are here in alphabetical order for convenience.
-->
<!-- ================================================================= -->


<!ELEMENT Field            (#PCDATA)>	<!-- .+ -->

<!ELEMENT OP               (#PCDATA)>	<!-- (AND|OR|NOT|RANGE|GROUP) -->

<!--~~ <Result>
This is the root element for a response.
~~ tags
  root
~~ json
<json resulttype='sample3' version='0.2' />
~~-->
<!ELEMENT Result ( TranslationStack? )>

<!ELEMENT Term             (#PCDATA)>	<!-- .+ -->

<!ELEMENT TermSet          (Term, Field)>


<!--~~ <TranslationStack>
This one is special because it can take any number of TermSet and/or OP
children, in any order.  In sample2, we converted this into an array.
This time, we'll convert it into a fancy tree structure, in custom templates
implemented in a custom stylesheet.
~~json
<ignore/>
~~-->
<!ELEMENT TranslationStack ((TermSet|OP)*)>

=== Global19/DtdAnalyzer/test/xml2json/sample3.xml
<?xml version="1.0" ?>
<!DOCTYPE Result SYSTEM "sample3.dtd">
<Result>
  <TranslationStack>
    <TermSet>
      <Term>"neoplasms"[MeSH Terms]</Term>
      <Field>MeSH Terms</Field>
    </TermSet>
    <TermSet>
      <Term>"neoplasms"[All Fields]</Term>
      <Field>All Fields</Field>
    </TermSet>
    <OP>OR</OP>
    <TermSet>
      <Term>"cancer"[All Fields]</Term>
      <Field>All Fields</Field>
    </TermSet>
    <OP>OR</OP>
    <OP>GROUP</OP>
    <TermSet>
      <Term>2012/09/25[EDAT]</Term>
      <Field>EDAT</Field>
    </TermSet>
    <TermSet>
      <Term>2012/11/24[EDAT]</Term>
      <Field>EDAT</Field>
    </TermSet>
    <OP>RANGE</OP>
    <OP>AND</OP>
  </TranslationStack>
</Result>
