=== Global19/DtdAnalyzer/test/xml2json/sample1.dtd
<!--
  This is a sample DTD for testing basic features of the XML-to-JSON
  funcionality of the DtdAnalyzer.
  
  This example is very simple
-->

<!-- ================================================================= -->

<!--~~ <Result>
This is the root element for a response.
~~ tags
root
~~-->
<!ELEMENT Result      (DbList,DbInfo?)>

<!ELEMENT DbList      (DbName+)>
<!ELEMENT DbName      (#PCDATA)>      <!-- \S+ -->

<!ELEMENT DbInfo      (DbName, MenuName, Description)>

<!ELEMENT MenuName    (#PCDATA)>      <!-- .+ -->
<!ELEMENT Description (#PCDATA)>      <!-- .+ -->

=== Global19/DtdAnalyzer/test/xml2json/sample1.xml
<?xml version="1.0"?>
<!DOCTYPE Result SYSTEM "sample1.dtd">
  
<Result>
  <DbList>
    <DbName>pubmed</DbName>
    <DbName>protein</DbName>
    <DbName>nuccore</DbName>
    <DbName>nucleotide</DbName>
  </DbList>
  <DbInfo>
    <DbName>pubmed</DbName>
    <MenuName>PubMed</MenuName>
    <Description>PubMed bibliographic record</Description>
  </DbInfo>
</Result>
