=== Global19/DtdAnalyzer/test/compare/test1.dtd
<!ELEMENT root ANY>
<!ELEMENT empty EMPTY>

<!-- 
  According to the spec, both 'pcdata' and 'mixed' here have "mixed content", but
  we'll use the term "pcdata" when only text nodes are allowed within an element.
-->
<!ELEMENT pcdata (#PCDATA)>
<!ELEMENT mixed (#PCDATA|empty|pcdata|mixed)*>

<!--
  All of the following have "children" content.  The productions are (neglecting 
  whitespace):
    children ::= (choice | seq) ('?' | '*' | '+')
    cp       ::= (Name | choice | seq) ('?' | '*' | '+')
    choice   ::= '(' cp ( '|' cp )* ')'
    seq      ::= '(' cp ( ',' cp )* ')'
-->
<!ELEMENT choice1 (chapter|appendix)+>
<!ELEMENT choice2 (chapter|appendix)?>
<!ELEMENT choice3 (chapter|appendix)*>
<!-- Nested choice -->
<!ELEMENT choice4 (chapter | (choice1 | choice2 | choice3)+)>

<!ELEMENT seq1 (chapter+, appendix+, glossary*)+>
<!ELEMENT seq2 (chapter+, (choice1 | choice2), (seq1, seq2?)+)?>

<!ELEMENT  chapter (#PCDATA)>
<!ELEMENT  appendix (#PCDATA)>
<!ELEMENT  glossary (#PCDATA)>

<!ELEMENT article (abstract?,(intro|preface),section+)?>

=== Global19/DtdAnalyzer/test/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  This sample tests various features of the DtdAnalyzer.
-->
<!DOCTYPE root SYSTEM "test1.dtd">
  

<root>
  <empty></empty>
  <empty/>

  <pcdata>Jackdaws love my big sphinx of quartz.</pcdata>
  
  <mixed><empty/>Jackdaws love my big sphinx of <pcdata>quartz</pcdata>.</mixed>
  
  <choice1>
    <chapter/><appendix/><appendix/><chapter/> 
  </choice1>
  <choice2><chapter/></choice2>
  <choice2><appendix/></choice2>
  <choice3/>
  <choice4><chapter/></choice4>
  <choice4>
    <choice1><chapter/></choice1>
    <choice2/>
    <choice1><appendix/></choice1>
  </choice4>
  
  <seq1><chapter/><chapter/><appendix/></seq1>
  <seq2><chapter/><chapter/><choice2/><seq1><chapter/><appendix/></seq1></seq2>
</root>
